# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ThreeME
tagline:          'OFCE'
description:      'Menu'
url:              http://lanyon.getpoole.com
baseurl:          'lidewey.github.io'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
