# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Three-ME
tagline:          'OFCE'
description:      'Menu'
url:              http://lanyon.getpoole.com
baseurl:          '/News'
paginate:         5

author:
  name:           'Lidewey van der Wal'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
